adam_beta1: 0.9
adam_beta2: 0.95
bs: 64
cyclic_lr_initial: 1.0e-05
cyclic_n_cycles: 2
data:
  buffer_size: 1024
  shuffle: true
  test_tfrecords_path: ./data/tfrecords/test.tfrecords
  train_tfrecords_path: ./data/tfrecords/train.tfrecords
eager: true
epochs: 2
exp_name: debug
gpus:
- -1
load_optim_pth: null
load_weights_pth: null
log:
  batch_freq: 20
  enable_async: true
  image_grid: false
loss: crossentropy
lr: 0.0003
lr_method: cyclic
metric1: accuracy
model:
  dropout1: 0.25
  dropout2: 0.5
  fc_units: 128
  in_channels: 1
  model_class: BabyCNN
  out_features: 10
run_name: run_0
save_best: false
save_init: false
save_last: false
seed: 42
steps: null
weight_decay: 0.0
